
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Label
import subprocess
import json

# from HomePage import handle_login_success  

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\\Users\\jasmi\\Downloads\\VISKOM VSCODE\\UAS\\main\\assets\\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#000000")


canvas = Canvas(
    window,
    bg = "#000000",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    720.0,
    1024.0,
    fill="#D9D9D9",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    360.0,
    500.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    850.0,
    450.0,
    image=image_image_2
)

canvas.create_rectangle(
    640.0,
    0.0,
    800.0,
    1024.0,
    fill="#000000",
    outline="")

canvas.create_text(
    988.0,
    180.0,
    anchor="nw",
    text="Holla,\nWelcome Back",
    fill="#FFFFFF",
    font=("OpenSansHebrewCondensed Bold", 48 * -1)
)

entry_1 = Entry(
    bd=0,
    bg="#000000",
    fg="#FFFFFF",
    highlightthickness=0,
    insertbackground="#FFFFFF",
)
entry_1.place(
    x=988.0,
    y=486.0,
    width=280.0,
    height=30.0
)

entry_2 = Entry(
    bd=0,
    bg="#000000",
    fg="#FFFFFF",
    highlightthickness=0,
    insertbackground="#FFFFFF"
)
entry_2.place(
    x=988.0,
    y=550.0,
    width=280.0,
    height=30.0
)

text_username = canvas.create_text(
    958.0,
    465.0,
    anchor="nw",
    text="    Username",
    fill="#FFFFFF",  
    font=("OpenSansHebrewCondensed Bold", 24 * -1)
)

text_password = canvas.create_text(
    985.0,
    525.0,
    anchor="nw",
    text="Password",
    fill="#FFFFFF",
    font=("OpenSansHebrewCondensed Bold", 24 * -1),
)

canvas.create_text(
    1010.0,
    750,
    anchor="nw",
    text="Don't have an account? ",
    fill="#FFFFFF",
    font=("OpenSansHebrewCondensed Bold", 16 * -1)
)

text_registration = canvas.create_text(
    1180.0,
    750,
    anchor="nw",
    text="Registration",
    fill="#44AF0F",
    font=("OpenSansHebrewCondensed Bold", 14 * -1)
)

text_forget_password = canvas.create_text(
    1085.0,
    583.0,
    anchor="nw",
    text="                           Forget password?",
    fill="#FFFFFF",
    font=("OpenSansHebrewCondensed Bold", 12 * -1)
)

login = canvas.create_rectangle(
    988.0,
    630.0,
    1268.0,
    680.0,
    fill="#12480E",
    outline="")

canvas.create_text(
    990.0,
    640.0,
    anchor="nw",
    text="                  Login",
    fill="#FFFFFF",
    font=("OpenSansHebrewCondensed Bold", 20 * -1)
)

# Binding event handler untuk teks Forget password?
canvas.tag_bind(text_forget_password, "<Button-1>", lambda event: handle_forget_password_click())
canvas.tag_bind(text_registration, "<Button-1>", lambda event: handle_registration_click())
canvas.tag_bind(login, "<Button-1>", lambda event: handle_login_click())

def handle_registration_click():
    # Logika untuk menangani klik pada tombol Registration
    print("Navigating to registration page")
    window.quit()
    window.destroy()
    subprocess.run(["python", "C:\\Users\\jasmi\\Downloads\\VISKOM VSCODE\\UAS\\main\\2_Regis.py"])
    
def handle_forget_password_click():
    # Logika untuk menangani klik pada teks Forget password?
    print("Navigating to forget password page")
        
def handle_login_click():
    
    # # Logika untuk menangani klik pada tombol Login
    username = entry_1.get()
    password = entry_2.get()


    success, user_data = log_in(username, password)
        
    if success:
        print("Login successful")
        window.quit()
        window.destroy()

        with open("userdata.json", "w") as user_file:
            json.dump(user_data, user_file)

        subprocess.run(["python", "C:\\Users\\jasmi\\Downloads\\VISKOM VSCODE\\UAS\\main\\7_HomePage.py", *user_data])
    else:
        print("Invalid username or password")

        
def on_enter_reg(event):
    canvas.itemconfig(text_registration, fill="#FFFFFF")

def on_enter_login(event):
    canvas.itemconfig(login, fill="#0D350A")

def on_enter_forget(event):
    canvas.itemconfig(text_forget_password, fill="#12480E")

def on_leave_reg(event):
  canvas.itemconfig(text_registration, fill="#44AF0F")
  
def on_leave_login(event):
  canvas.itemconfig(login, fill="#12480E")

def on_leave_forget(event):
  canvas.itemconfig(text_forget_password, fill="#FFFFFF")

canvas.tag_bind(text_registration, "<Enter>", on_enter_reg)
canvas.tag_bind(text_registration, "<Leave>", on_leave_reg)
canvas.tag_bind(login, "<Enter>", on_enter_login)
canvas.tag_bind(login, "<Leave>", on_leave_login)
canvas.tag_bind(text_forget_password, "<Enter>", on_enter_forget)
canvas.tag_bind(text_forget_password, "<Leave>", on_leave_forget)

canvas.create_rectangle(
    987.0,
    518.0,
    1268.0000138282758,
    519.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    988.0,
    583.0,
    1268.0000138282758,
    583.0,
    fill="#FFFFFF",
    outline="")

# canvas.create_rectangle(
#     988.0,
#     630.0,
#     1268.0,
#     680.0,
#     fill="#12480E",
#     outline="")

# canvas.create_text(
#     988.0,
#     640.0,
#     anchor="nw",
#     text="                  Login",
#     fill="#FFFFFF",
#     font=("OpenSansHebrewCondensed Bold", 20 * -1)
# )

def log_in(username, password):
    success = False
    user_data = None  # Initialize user_data to None

    with open("C:\\Users\\jasmi\\Downloads\\VISKOM VSCODE\\UAS\\logindatabase.txt", "r") as file:
        for line in file:
            data = line.strip().split(",")
            if len(data) >= 3:
                stored_username, stored_password = data[1], data[2]

                if stored_username == username and stored_password == password:
                    success = True
                    user_data = [data[0], stored_username, stored_password]  # Incorrect: Storing only the first element as an integer
                    break

    return success, user_data

window.resizable(False, False)
window.mainloop()